services:
  mysql:
    container_name: mysql-container
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rtp
      - MYSQL_PASSWORD=rtp
      - MYSQL_DATABASE=shopping_cart_management_db
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin:5.2.1
    ports:
      - "8090:80"
    networks:
      - mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopping_cart_management_db
      - MYSQL_USER=rtp
      - MYSQL_PASSWORD=rtp
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: unless-stopped

  shoppingcart-app:
    container_name: shoppingcart-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopping_cart_management_db
      - SPRING_DATASOURCE_USERNAME=rtp
      - SPRING_DATASOURCE_PASSWORD=rtp
      - SPRING_JPA_DATABASE=mysql
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    restart: unless-stopped

networks:
  mysql:
    driver: bridge